# Eye On Hand

In [3]:
import pickle
data_path = 'dataset/flexiv/ef_camera.pkl'
with open(data_path, 'rb') as f:
    data = pickle.load(f)
data.keys()

dict_keys(['imgs', 'params', 'robot_poses'])

In [11]:
data['imgs'][0].shape

(720, 1280, 3)

In [7]:
import numpy as np
K=data['params']['RGB']['K']
D = data['params']['RGB']['D']

In [8]:
from SimpleHandEye.interfaces.apriltag import ApriltagTracker
tracker = ApriltagTracker(tag_size=0.153,
                          intrinsic_matrix=K,
                          distortion_coeffs=D)

In [12]:
import cv2
image_poses=[]
robot_poses=[]
for i,img in enumerate(data['imgs']):
    robot_pose = data['robot_poses'][i]
    # cv2.imwrite(f'flexiv_dataset/{i}.png', item[1])
    image_pose = tracker.getPose(img, tag_id=0)
    if image_pose is not None:
        image_poses.append(image_pose)
        robot_poses.append(robot_pose)
    

In [13]:
from SimpleHandEye.solvers import OpenCVSolver

In [14]:
solver = OpenCVSolver()

In [15]:
A = robot_poses # Pose of the hand with respect to the base
B = [np.linalg.inv(T) for T in image_poses]

X, Y = solver.solve(A, B)

In [16]:
X, Y

(array([[-0.01147745, -0.99985254,  0.01277383,  0.08960414],
        [ 0.99987984, -0.011609  , -0.01027274, -0.03007833],
        [ 0.01041951,  0.01265439,  0.99986564,  0.07234493],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([[-0.00815669, -0.99991112,  0.01054607,  0.51429557],
        [-0.99996512,  0.00817519,  0.00171209,  0.01612239],
        [-0.00179815, -0.01053174, -0.99994292,  0.00126261],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]))

In [17]:
hand_T_cam = X

In [19]:
for i in range(len(A)):
    print(np.linalg.norm((A[i]@X@np.linalg.inv(Y@B[i]))[:3,-1]))

0.004900929989746712
0.004798079676462854
0.008547323071457598
0.008468821461449514
0.0012283538460332601
0.0012124624274551178
0.0011141172106898711
0.01208803206146044
0.012132634475683596
0.005611235666339801
0.0050853487287546555
0.0118936940573681
0.001082146663574132
0.001119671205077208
0.001729989510170798
0.001867635796229327
0.0023647844419426543
0.0023522394488654373
0.014175208183969341
0.014109646045081258
0.010118952483144043
0.009761801963849308
0.004320886880907761
0.004260022201976727
0.017033282416446145
0.0169113737122366
0.016879889451858976
0.003435284846413428
0.0033898788219963788
0.002827861447239284
0.002932142305817547
0.002100743826801098
0.00182355654675731
0.0020347145501043175
0.0018823163327218602
0.002744057012963093
0.002766640954489436
0.004036089767568295
0.004169906477893781


In [20]:
output_path = data_path.split('.')[0]+'_result.pkl'
with open(output_path, 'wb') as f:
    pickle.dump(hand_T_cam, f)

# Eye on Base

In [21]:
import pickle
data_path = 'dataset/flexiv/left_camera.pkl'
with open(data_path, 'rb') as f:
    data = pickle.load(f)
data.keys()

dict_keys(['imgs', 'params', 'robot_poses'])

In [30]:
import numpy as np
K=data['params']['RGB']['K']
D = data['params']['RGB']['D']
tag_id = 1
tag_size = 0.153

In [23]:
from SimpleHandEye.interfaces.apriltag import ApriltagTracker
tracker = ApriltagTracker(tag_size=tag_size,
                          intrinsic_matrix=K,
                          distortion_coeffs=D)

In [29]:
import cv2
image_poses=[]
robot_poses=[]
for i,img in enumerate(data['imgs']):
    robot_pose = data['robot_poses'][i]
    # cv2.imwrite(f'flexiv_dataset/{i}.png', item[1])
    image_pose = tracker.getPose(img, tag_id=tag_id)
    if image_pose is not None:
        print(i)
        image_poses.append(image_pose)
        robot_poses.append(robot_pose)
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [25]:
from SimpleHandEye.solvers import OpenCVSolver

In [26]:
solver = OpenCVSolver()

In [27]:
A = robot_poses # Pose of the hand with respect to the base
B = [np.linalg.inv(T) for T in image_poses]

X, Y = solver.solve(A, B)

AssertionError: A and B must have at least 3 elements

In [ ]:
X, Y

(array([[-0.01147745, -0.99985254,  0.01277383,  0.08960414],
        [ 0.99987984, -0.011609  , -0.01027274, -0.03007833],
        [ 0.01041951,  0.01265439,  0.99986564,  0.07234493],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([[-0.00815669, -0.99991112,  0.01054607,  0.51429557],
        [-0.99996512,  0.00817519,  0.00171209,  0.01612239],
        [-0.00179815, -0.01053174, -0.99994292,  0.00126261],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]))

In [ ]:
hand_T_cam = X

In [ ]:
for i in range(len(A)):
    print(np.linalg.norm((A[i]@X@np.linalg.inv(Y@B[i]))[:3,-1]))

0.004900929989746712
0.004798079676462854
0.008547323071457598
0.008468821461449514
0.0012283538460332601
0.0012124624274551178
0.0011141172106898711
0.01208803206146044
0.012132634475683596
0.005611235666339801
0.0050853487287546555
0.0118936940573681
0.001082146663574132
0.001119671205077208
0.001729989510170798
0.001867635796229327
0.0023647844419426543
0.0023522394488654373
0.014175208183969341
0.014109646045081258
0.010118952483144043
0.009761801963849308
0.004320886880907761
0.004260022201976727
0.017033282416446145
0.0169113737122366
0.016879889451858976
0.003435284846413428
0.0033898788219963788
0.002827861447239284
0.002932142305817547
0.002100743826801098
0.00182355654675731
0.0020347145501043175
0.0018823163327218602
0.002744057012963093
0.002766640954489436
0.004036089767568295
0.004169906477893781


In [ ]:
with open('flexiv_link7_T_camera.pkl', 'wb') as f:
    pickle.dump(hand_T_cam, f)