# AX=YB
This notebook shows the process of calibrating the extrinsic parameters between the Vicon marker coordinate frame installed on an object with respect to the object CAD coordinate frame. We use the ICG 3D tracker algorithm to track the 3D pose of the object through its pointcloud observation and the ROS2 vicon bridge to get the pose of the markers installed on it.

In [ ]:
from SimpleHandEye.interfaces.utils import addFoxyPath
addFoxyPath('/opt/ros/foxy')

In [ ]:
from SimpleHandEye.interfaces.ros2 import ROS2TFInterface
import rclpy
rclpy.init()    
tf_interface = ROS2TFInterface('world', 'base_link')

In [ ]:
tf_interface.getPose()

In [ ]:
from SimpleHandEye.interfaces.cameras import RealSenseCamera
import cv2

def showImage(color_frame, depth_frame, ir1_frame, ir2_frame):
    cv2.imshow('image', color_frame)
    cv2.waitKey(1)

camera = RealSenseCamera(callback_fn=showImage)

intrinsics_params = camera.getIntrinsics()
K = intrinsics_params['RGB']['K']
D = intrinsics_params['RGB']['D']

In [ ]:
from SimpleHandEye.interfaces.apriltag import ApriltagTracker
tracker = ApriltagTracker(tag_size=0.12,
                          intrinsic_matrix=K,
                          distortion_coeffs=D)

tracker.getPose(camera.color_frame, tag_id=0)

In [ ]:
from SimpleHandEye.solvers import OpenCVSolver
solver = OpenCVSolver()

In [27]:
import ipywidgets as widgets
import numpy as np
from IPython.display import display
from pprint import pprint
np.set_printoptions(suppress=True, precision=3)

# The dataset
A_list = []
B_list = []

def on_sample_clicked(b):
    A = tracker.getPose(camera.color_frame, tag_id=0)
    B = tf_interface.getPose()
    print("A=")
    pprint(A)
    print("B=")
    pprint(B)
    # if A is not None and B is not None:
    A_list.append(A)
    B_list.append(B)
    print("*************")

def on_compute_clicked(b):
    try:
        X,Y = solver.solve(A_list, B_list)
        print("X=")
        pprint(X)
        print("Y=")
        pprint(Y)
    except:
        print("Bad dataset, please record again")
        A_list.clear()
        B_list.clear()
        

sample_button = widgets.Button(description="Sample")
compute_button = widgets.Button(description="Compute")

sample_button.on_click(on_sample_clicked)
compute_button.on_click(on_compute_clicked)
display(sample_button)
display(compute_button)

Button(description='Sample', style=ButtonStyle())

Button(description='Compute', style=ButtonStyle())

A=
array([[ 0.978,  0.165, -0.129, -0.028],
       [-0.163,  0.986,  0.02 ,  0.029],
       [ 0.13 ,  0.001,  0.991,  0.401],
       [ 0.   ,  0.   ,  0.   ,  1.   ]])
B=
None
*************
A=
array([[ 0.978,  0.165, -0.128, -0.028],
       [-0.163,  0.986,  0.02 ,  0.029],
       [ 0.129,  0.001,  0.992,  0.401],
       [ 0.   ,  0.   ,  0.   ,  1.   ]])
B=
None
*************
A=
array([[ 0.978,  0.165, -0.127, -0.028],
       [-0.163,  0.986,  0.022,  0.029],
       [ 0.129, -0.   ,  0.992,  0.401],
       [ 0.   ,  0.   ,  0.   ,  1.   ]])
B=
None
*************
A=
array([[ 0.978,  0.165, -0.127, -0.028],
       [-0.163,  0.986,  0.021,  0.029],
       [ 0.129,  0.   ,  0.992,  0.401],
       [ 0.   ,  0.   ,  0.   ,  1.   ]])
B=
None
*************
A=
array([[ 0.978,  0.165, -0.128, -0.028],
       [-0.163,  0.986,  0.021,  0.029],
       [ 0.129,  0.001,  0.992,  0.401],
       [ 0.   ,  0.   ,  0.   ,  1.   ]])
B=
None
*************
A=
array([[ 0.978,  0.165, -0.127, -0.028],
      